name: ThinFlux Demo Lab

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      # Mapeia o diretório atual do GitHub Workspace para coletar o JSON gerado
      - name: Run ThinFlux (Optimization Step)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/demo/assets:/data \
            -v ${{ github.workspace }}:/app \
            -w /app \
            betoxvt/thinflux:latest run /data --summary

      # Busca arquivo gerado e disponibiliza para download na aba Summary do Workflow.
      - name: Upload Telemetry Report Only
        uses: actions/upload-artifact@v4
        with:
          name: thinflux-telemetry-report
          path: thinflux_report.json
          if-no-files-found: error

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "./demo"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
